import { ImmunityMatrix, MatrixDrawer, type TestCase } from '../components/ImmunityMatrix';
import React, { useEffect, useState, useRef } from 'react';
import { useParams } from 'react-router-dom';
import { taskService } from '../api/services';
import Layout from '../components/Layout';
import { Play, Square, UploadCloud, Terminal, Clock, Activity, Target } from 'lucide-react';
import { RiskPanel } from '../components/RiskPanel';
import { CodeSection } from '../components/CodeSection';

export default function ExecutionPage() {
  const { id } = useParams<{ id: string }>();
  const [task, setTask] = useState<any>(null);
  const [logs, setLogs] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const logEndRef = useRef<HTMLDivElement>(null);
  
  // 抽屉状态
  const [selectedCase, setSelectedCase] = useState<TestCase | null>(null);

  // 模拟的矩阵数据 (在后端完全就绪前先 Mock 一下效果)
  const [matrixCases, setMatrixCases] = useState<TestCase[]>([]);

  useEffect(() => { fetchDetail(); }, [id]);

  // 轮询逻辑
  useEffect(() => {
    let interval: any;
    if (task?.status === 'running') {
      interval = setInterval(() => {
        fetchDetail(false);
        fetchLogs();
      }, 2000);
    }
    return () => clearInterval(interval);
  }, [task?.status]);

  // 自动滚动日志
  useEffect(() => {
    logEndRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [logs]);

  // 生成模拟矩阵数据逻辑 (根据 Task 状态变化)
  useEffect(() => {
    if (!task) return;
    
    // 如果有 Slither 报告，生成几个 "Static" 用例
    const newCases: TestCase[] = [];
    
    // 1. Slither 来源 (High/Medium)
    if (task.slither_report) {
      newCases.push({
        id: '101', source: 'SLITHER', 
        status: task.codes?.fix ? 'PASSING' : 'FAILING', // 有修复代码就算修好了
        name: 'Reentrancy', description: 'Detected via Static Analysis', 
        code: `function testReentrancy() {\n  // Exploit logic \n}`
      });
      newCases.push({
        id: '102', source: 'SLITHER', 
        status: task.codes?.fix ? 'PASSING' : 'FAILING', 
        name: 'Unchecked Low Level Call', description: 'Detected via Static Analysis', 
        code: `function testCall() {\n  // Exploit logic \n}`
      });
    }

    // 2. 红方攻击来源 (Exploit Code)
    if (task.codes?.exploit) {
      newCases.push({
        id: '201', source: 'RED_TEAM',
        status: task.codes?.fix ? 'PASSING' : 'FAILING',
        name: 'Composite Attack', description: 'Generated by RedAgent based on findings',
        code: task.codes.exploit
      });
    }

    // 3. 模拟一些正在生成的方块
    if (task.status === 'running') {
      // 保持之前的 cases
    }
    
    setMatrixCases(newCases);

  }, [task]);

  const fetchDetail = async (showLoading = true) => {
    if (showLoading) setLoading(true);
    try {
      const res = await taskService.getDetail(id!);
      setTask(res.data);
      if (showLoading) fetchLogs();
    } catch (err) {
       console.error(err);
    } finally {
      if (showLoading) setLoading(false);
    }
  };

  const fetchLogs = async () => {
    try {
      const res = await taskService.getLogs(id!);
      setLogs(res.data);
    } catch (err) {}
  };

  // 控制操作
  const handleUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files[0]) {
      await taskService.upload(id!, e.target.files[0]);
      fetchDetail();
    }
  };
  const handleStart = async () => await taskService.start(id!).then(() => fetchDetail());
  const handleStop = async () => await taskService.stop(id!).then(() => fetchDetail());
  const formatTime = (time: string) => time ? new Date(time).toLocaleTimeString('en-GB') : '--:--:--';

  if (loading || !task) return <div className="flex h-screen items-center justify-center">Loading Mission Control...</div>;

  return (
    <div className="h-screen flex flex-col bg-slate-50 text-slate-900 font-sans overflow-hidden">
      {/* 1. Top Bar: Dashboard Header */}
      <header className="bg-white border-b border-slate-200 px-6 py-3 flex justify-between items-center shadow-sm z-10">
        <div className="flex items-center gap-4">
           <div className="bg-indigo-600 p-2 rounded-lg text-white">
             <Target className="w-5 h-5" />
           </div>
           <div>
             <h1 className="text-lg font-bold text-slate-800 flex items-center gap-2">
               {task.name}
               <span className={`px-2 py-0.5 rounded text-xs uppercase ${task.status === 'running' ? 'bg-amber-100 text-amber-700 animate-pulse' : 'bg-slate-100 text-slate-600'}`}>
                 {task.status}
               </span>
             </h1>
             <p className="text-xs text-slate-500 font-mono">ID: {task.id.substring(0,8)}...</p>
           </div>
        </div>

        {/* Stats Metrics */}
        <div className="flex gap-8">
           <div className="text-center">
             <div className="text-xs text-slate-400 font-bold uppercase">New Threats</div>
             <div className="text-xl font-bold text-amber-500">+2</div>
           </div>
           <div className="text-center">
             <div className="text-xs text-slate-400 font-bold uppercase">Coverage</div>
             <div className="text-xl font-bold text-indigo-600">85%</div>
           </div>
           <div className="text-center">
             <div className="text-xs text-slate-400 font-bold uppercase">Total Cases</div>
             <div className="text-xl font-bold text-slate-700">{matrixCases.length}</div>
           </div>
        </div>

        {/* Controls */}
        <div className="flex gap-2">
          {['created', 'failed', 'completed'].includes(task.status) && (
            <div className="relative">
              <input type="file" onChange={handleUpload} className="absolute inset-0 w-full h-full opacity-0 cursor-pointer" />
              <button className="flex items-center px-4 py-2 border border-slate-300 bg-white rounded-lg text-slate-700 hover:bg-slate-50 text-sm font-medium transition-colors">
                <UploadCloud className="w-4 h-4 mr-2" /> Upload
              </button>
            </div>
          )}
          {['created', 'uploaded', 'stopped', 'completed', 'failed'].includes(task.status) && task.contract_name && (
            <button onClick={handleStart} className="flex items-center px-6 py-2 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700 shadow-md shadow-indigo-200 transition-all active:scale-95">
              <Play className="w-4 h-4 mr-2 fill-current" /> Start Audit
            </button>
          )}
          {task.status === 'running' && (
            <button onClick={handleStop} className="flex items-center px-6 py-2 bg-red-500 text-white rounded-lg hover:bg-red-600 shadow-md shadow-red-200 transition-all">
              <Square className="w-4 h-4 mr-2 fill-current" /> Stop
            </button>
          )}
        </div>
      </header>

      {/* 2. Main Content Grid */}
      <main className="flex-1 p-4 grid grid-cols-12 gap-4 overflow-hidden relative">
        
        {/* Left: Risk Discovery (3 cols) */}
        <div className="col-span-3 h-full overflow-hidden">
          <RiskPanel 
            slitherReport={task.slither_report} 
            fuzzerStats={{ total: 1205, passed: 1203 }} // Mock data until backend sends it
          />
        </div>

        {/* Center: Immunity Matrix (5 cols) */}
        <div className="col-span-5 h-full overflow-hidden relative">
          <ImmunityMatrix cases={matrixCases} onSelectCase={setSelectedCase} />
          {/* Drawer Overlay */}
          <MatrixDrawer testCase={selectedCase} onClose={() => setSelectedCase(null)} />
        </div>

        {/* Right: Code & Diff (4 cols) */}
        <div className="col-span-4 h-full overflow-hidden">
          <CodeSection 
            originalCode={task.codes?.original} 
            fixedCode={task.codes?.fix} 
            contractName={task.contract_name} 
          />
        </div>

      </main>

      {/* 3. Bottom: System Logs */}
      <div className="h-48 bg-[#1e1e1e] border-t border-slate-700 flex flex-col shrink-0">
        <div className="px-4 py-1 bg-[#2d2d2d] flex items-center justify-between">
           <div className="flex items-center text-xs text-slate-400">
             <Terminal className="w-3 h-3 mr-2" /> System Console
           </div>
           <div className="flex items-center text-xs text-slate-500 gap-3">
             <span className="flex items-center"><Activity className="w-3 h-3 mr-1"/> Live</span>
             <span className="flex items-center"><Clock className="w-3 h-3 mr-1"/> {new Date().toLocaleTimeString()}</span>
           </div>
        </div>
        <div className="flex-1 overflow-y-auto p-2 font-mono text-xs space-y-1">
           {logs.map((log, i) => (
             <div key={i} className="flex hover:bg-[#2a2d2e]">
               <span className="text-slate-500 w-20 shrink-0 border-r border-slate-700 mr-2">{formatTime(log.time)}</span>
               <span className={`${log.level === 'ERROR' || log.content.includes('TRUE_POSITIVE') ? 'text-red-400' : log.content.includes('VERIFIED') ? 'text-emerald-400' : 'text-slate-300'}`}>
                 {log.content}
               </span>
             </div>
           ))}
           <div ref={logEndRef} />
        </div>
      </div>
    </div>
  );
}